/* Hovertank 3-D Source Code
 * Copyright (C) 1993-2014 Flat Rock Software
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

//
// From Sound Editor v1.31 by Lane Roath
//

#define FIRESND 1
#define BUMPWALLSND 2
#define AFTERBURNSND 3
#define SHOOTWALLSND 4
#define SHOOTTHINGSND 5
#define SAVEHOSTAGESND 6
#define HOSTAGEDEADSND 7
#define LOWTIMESND 8
#define TAKEDAMAGESND 9
#define NUKESND 10
#define WARPGATESND 11
#define PLAYERDEADSND 12
#define GUNREADYSND 13
#define MAXPOWERSND 14
#define LASTHOSTAGESND 15
#define ARMORUPSND 16
#define TIMESCORESND 17
#define GUYSCORESND 18
#define STARTGAMESND 19
#define HIGHSCORESND 20
